REL-483701 - Added Relativity.Kepler.dll to default files to be inclu…
relativitydev/relativity-dev-vm pull request #130
Opened 2020-11-06 21:49 UTC by aarongilbert123

…ded in Powershell Module Folder

2020-11-06 22:31 UTC, calimetikcura requested changes

2020-11-06 22:31 UTC, calimetikcura commented on Chef/Cookbooks/Relativity/recipes/post_relativity_powershell_module_setup.rb
> +  "Relativity.Kepler.dll"
I am not sure if this is the right solution. It seems like a workaround for today. This solution might not work in future where we would require a higher version of Relativity.Kepler as we are hardcoding the Kepler to version 2.7. 
@aarongilbert123 Can we discuss about this offline?

2020-11-09 17:07 UTC, calimetikcura approved these changes

2020-11-09 17:07 UTC, calimetikcura commented on Chef/Cookbooks/Relativity/recipes/post_relativity_powershell_module_setup.rb
> +  "Relativity.Kepler.dll"
discussed offline.

2020-11-09 17:14 UTC, jake-martin approved these changes

2020-11-09 17:15 UTC, merged