Rel-507459 update applicationinstallhelper with rest
relativitydev/relativity-dev-vm pull request #137
Opened 2021-01-11 20:59 UTC by TommyBigNose

2021-01-11 21:35 UTC, calimetikcura requested changes

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/DevVmPsModules/Cmdlets/AddApplicationFromLibraryModule.cs
> +			RestHelper restHelper = new RestHelper();
- [ ] Aaron created an interface IRestHelper, Can we use that instead to pass to the various Helper constructors?

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/ApplicationInstallHelper.cs
> +		private async Task<int> GetApplicationLibraryId(string applicationGuid)
- [ ] Add Async suffix

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/ApplicationInstallHelper.cs
> +		private async Task<HttpResponseMessage> UpdateLibraryApplication(HttpClient httpClient, string filePath)
- [ ] Should the method name be Upload instead?

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/ApplicationInstallHelper.cs
> +		private async Task<HttpResponseMessage> UpdateLibraryApplication(HttpClient httpClient, string filePath)
- [ ] Add Async suffix

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/ApplicationInstallHelper.cs
> +		private async Task<bool> InstallApplicationOnWorkspace(HttpClient httpClient, string workspaceName, int applicationId)
- [ ] Add Async suffix

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/RetryLogicHelper.cs
> +			if (numberOfRetries < 0) throw new ArgumentException($"Parameter {nameof(numberOfRetries)} cannot be null or less than 0.");
- [ ] remove cannot be null from the message

2021-01-11 21:35 UTC, calimetikcura commented on CSharp/DevVmPowershell/Helpers/Implementations/RetryLogicHelper.cs
> +			if (delayInSeconds < 0) throw new ArgumentException($"Parameter {nameof(delayInSeconds)} cannot be null or less than 0.");
- [ ] remove cannot be null from the message

2021-01-11 22:46 UTC, calimetikcura approved these changes

2021-01-12 00:42 UTC, aarongilbert123 approved these changes

2021-01-12 13:20 UTC, merged