REL-527051 | Removed the RSAPI package and reference in solution
relativitydev/relativity-dev-vm pull request #166
Opened 2021-02-19 20:44 UTC by TommyBigNose

2021-02-19 20:45 UTC, aarongilbert123 approved these changes

2021-02-19 20:46 UTC, jake-martin submitted a review, later dismissed

2021-02-19 20:50 UTC, calimetikcura requested changes
Can we please update the Changelog file with the changes?

2021-02-23 01:27 UTC, calimetikcura approved these changes

2021-02-24 21:04 UTC, aarongilbert123 approved these changes

2021-02-24 21:05 UTC, merged